### PR TITLE
NSO update

### PR DESCRIPTION
**Pull request by gerad-not-edgar**
Well... this is what this looks like. Some are definitely better, but most come off as washed out since the current ones have been retouched significantly. Would be nice to have genesis more in line with some of the Nintendo systems as far as organization goes with these multiple region boxarts for the same game. Honestly hate working with these because of it. As far as I know it's been USA > Europe and Japan for nintendo. Honestly wouldn't mind trying to sort this out, adhering to the naming convention over trying keep every region of box art but I'm betting it would piss a lot of people off. Currently 6564 genesis orphans because of it. Any ideas @RobLoach ?

### CODE REVIEW

**Comment by RobLoach** [comment]
Oof, yeah. Many of these look like they've been super desaturated.

Screenshot at 2023-10-08 13-11-46


> Currently 6564 genesis orphans because of it.

For the orphans, it takes some manual renames to make them match.

**Comment by gerad-not-edgar** [comment]
Alright, this is all I have. If these look good, I'll consider tackling the orphans according to the current list once this PR is merged. Can pretty much guarantee it'll be a ton of deletions since most seem to have gone to (World).

**Comment by RobLoach** [comment]
@gerad-not-edgar  A few of these look a bit washed out compared to the originals. Was there any image processing done on them?

**Comment by gerad-not-edgar** [comment]
No, these are taken straight from Nintendo Switch online. I think the current ones are leaning more towards the oversaturated side, making these come off way worse than they are.

**Pull request closed without merging**
