### PR TITLE
Updated content + no-intro renaming

### PR DESCRIPTION
**Pull request by ner00**
Renames a few files to comply with no-intro database.

### CODE REVIEW

**Review by RobLoach — CHANGES_REQUESTED** [review]
I'm confused. It says no files changed?

**Comment by ner00** [comment]
Yeah, something went wrong here... I had a bunch of commits from late last year but forgot to do a pull request. Today I fetched from upstream (https://github.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/pull/37/commits/ff779f32912bb10838adcee809995e4b56492eb4) since there was no apparent conflict but now this looks like it is ignoring everything before that... not sure what to do, might have to tinker a bit with this.

**Comment by ner00** [comment]
Should be good now.

**Comment by RobLoach** [comment]
Wow, these are incredible.

**Comment by ner00** [comment]
Thanks! The renaming was hectic so I ended up creating individual commits to make it easier to revert just in case.

**Comment by RobLoach** [comment]
Hah, no need for individual commits, but it it makes it easier to you 👍

**Pull request merged**
