### PR TITLE
Multiple file renames to match no-intro db

### PR DESCRIPTION
**Pull request by ner00**
Also, some updated artwork

### CODE REVIEW

**Comment by ner00** [comment]
@RobLoach I think should maybe do things a bit differently next time. 
Maybe leave in the commit comment a direct link to the specific entry in no-intro Data-O-Matic web database for quicker validation on your side. Also, do you think it is preferable 40 commits = 40 pull requests or all-in-one as is?

Ia any suggestions, shoot.

**Comment by RobLoach** [comment]
> Maybe leave in the commit comment a direct link to the specific entry in no-intro Data-O-Matic web database for quicker validation on your side.

While it is appreciated, it is in no way required. Been a while since I ran it, but [libretro-thumbnails-check](https://github.com/robloach/libretro-thumbnails-check) will generate a report.

> Also, do you think it is preferable 40 commits = 40 pull requests or all-in-one as is?

You can have all the changes in one commit, if that makes it easier for you. When merging, GitHub UI gives you the option to squash in case there are re-writes.

**Comment by ner00** [comment]
Is this waiting for any change on my end? I'm assuming it's due to the big amount of changes and times it takes to go over it, but just thought I should ask in case I missed something.

**Comment by RobLoach** [comment]
Thanks so much @ner00 !

**Pull request merged**
