### PR TITLE
Add some missing art for common roms (nointro)

### PR DESCRIPTION
**Pull request by palmerj**
Roms:
- Contra - Hard Corps (USA, Korea) (En)
- Street Fighter II' - Hyper Champion Edition
- Thunder Force III (Japan, USA) (En)
- Ecco the Dolphin (USA, Europe, Korea) (En)

Some are just naming issues, so copies have been made. I've kept the existing ones for backwards compatibility for existing users

### CODE REVIEW

**Comment by i30817** [comment]
No-intro is changing the names to add more metadata. But as long as the database isn't updated, having duplicates like this 'ecco the dolphin (usa)' and 'ecco the dolphin (usa,europe,korea)' is probably the best way. One or the other will get deleted eventually once the orphan checking comes along.

**Comment by palmerj** [comment]
OK thanks. Is this ok to merge?

**Comment by i30817** [comment]
Probably. I don't have those permissions, so you'll have to wait a bit. Or a week, it varies.

**Comment by RobLoach** [comment]
Thanks so much for pushing these up! They look great.

**Comment by palmerj** [comment]
Thanks for merging. Do you know when the updates get pushed to https://thumbnails.libretro.com/? Is it not automatic?

**Comment by RobLoach** [comment]
I believe a cron is set up for it. Perhaps every other day? I also know the pages are cached on Cloudflare so it could be you're getting a cached page. Let's check tomorrow and see if it's up.

**Comment by palmerj** [comment]
Hi @RobLoach, some images still haven't turned up. e.g http://thumbnails.libretro.com/Sega - Mega Drive - Genesis/Named_Boxarts/Contra - Hard Corps (USA, Korea) (En).png

**Comment by i30817** [comment]
The ps1 images that were fixed a month ago (from those broken symbolic links) are also not showing here.

From my libretrofuzz utility (these are just the missing images for the games _I_ have, there are more missing):

```
i3@sleipnir:~/a/exult-git$ libretro-fuzz
 Which playlist do you want to download thumbnails for? Sony - PlayStation.lpl
 Which directory should be used to download thumbnails? Sony - PlayStation
 Press escape to quit, and most other non-meta keys to skip downloads
Sony - PlayStation.lpl -> Sony - PlayStation
Missing: https://thumbnails.libretro.com/Sony%20-%20PlayStation/Named_Titles/MediEvil%20%28USA%29.png
Missing: https://thumbnails.libretro.com/Sony%20-%20PlayStation/Named_Snaps/MediEvil%20%28USA%29.png
Missing: https://thumbnails.libretro.com/Sony%20-%20PlayStation/Named_Titles/MediEvil%20II%20%28USA%29.png
Missing: https://thumbnails.libretro.com/Sony%20-%20PlayStation/Named_Snaps/MediEvil%20II%20%28USA%29.png
i3@sleipnir:~/a/exult-git$ 

```

I'm not sure if this is cloudflare being very late with updating because i don't have access to the server directly. If one of you can open the links and get a real image instead of a 404 error, i guess it's my local cloudflare being terrible.

You can go down https://thumbnails.libretro.com/Sony%20-%20PlayStation/Named_Titles/ (for instance) and find the files with size '8' (really, anything less than 200 is suspect). Those are broken symlinks that weren't updated even with the repositories updated, or broken files that are updated in the repo but still not in the server, so the cron job is either not working, or cloudflare is being silly (to me, if you find all the links working...)

I know that there are also some ps2 images broken in the same way.

**Comment by palmerj** [comment]
Looks like I've found some more thumbnails missing via script. So I will prepare another PR, so hold off checking why the thumbnails are not published yet. 

```
python check_retroarch_thumbnails.py
https://thumbnails.libretro.com/Sega - Mega Drive - Genesis/Named_Boxarts/Thunder Force III (Japan, USA) (En).png does not exist
https://thumbnails.libretro.com/Sega - Mega Drive - Genesis/Named_Boxarts/Contra - Hard Corps (USA, Korea) (En).png does not exist
https://thumbnails.libretro.com/Sega - Mega Drive - Genesis/Named_Boxarts/Ecco the Dolphin (USA, Europe, Korea) (En).png does not exist
https://thumbnails.libretro.com/Sega - Mega Drive - Genesis/Named_Titles/ToeJam _ Earl (USA, Europe, Korea) (En).png does not exist
https://thumbnails.libretro.com/Sega - Mega Drive - Genesis/Named_Titles/Golden Axe III (Europe) (Virtual Console).png does not exist
https://thumbnails.libretro.com/Sega - Mega Drive - Genesis/Named_Snaps/ToeJam _ Earl (USA, Europe, Korea) (En).png does not exist
https://thumbnails.libretro.com/Sega - Mega Drive - Genesis/Named_Snaps/Sonic The Hedgehog 2 (World).png does not exist
https://thumbnails.libretro.com/Sega - Mega Drive - Genesis/Named_Snaps/Sonic The Hedgehog 3 (USA).png does not exist
https://thumbnails.libretro.com/Sega - Mega Drive - Genesis/Named_Snaps/Sonic The Hedgehog (USA, Europe).png does not exist
https://thumbnails.libretro.com/Sega - Mega Drive - Genesis/Named_Snaps/Golden Axe III (Europe) (Virtual Console).png does not exist
```

**Comment by i30817** [comment]
Check the ps2 one too, there were also some missing there. It's annoying how small mistakes that are already fixed on the repositories lag for so long after they're fixed.

Looks like something is 'wrong' with the cron job and it can't recognize those files are updated... or cloudflare is being exceptionally bad at updating the cache.

**Comment by palmerj** [comment]
I've create #45 for a few more common thumbnails missing.

@RobLoach any chance to merge that and then see why some of this PR's images are still not published? Maybe check the cloudfront settings?

**Comment by RobLoach** [comment]
There's likely something wrong with the cron. I won't be able to have a look within the next couple weeks.

**Comment by palmerj** [comment]
OK thank you. Are you able to point me to the cron. Maybe I can review the code?

**Comment by RobLoach** [comment]
Need to get into the server and check.... Have a look in a week, it might be up by then.

**Pull request merged**
